INSERT INTO ccrepo.PERUCOMPRAS_tema_consulta (nombre) VALUES
('Acceso al Sistema'),
('Acceso a la Información Pública'),
('Acreditación de Marca'),
('Actuaciones Preparatorias'),
('Actualización de datos'),
('Actualización de Recaudo'),
('Ampliación de Plazo de Entrega'),
('Ampliación de Publicación de OCAM'),
('Anexo 2 Proforma'),
('Anexo 3 Orden de Compra'),
('Bandeja de notificaciones'),
('Boletos Aéreos'),
('Búsqueda de fichas producto'),
('Canales de Atención'),
('Capacitación'),
('Carta de Originalidad'),
('Carta de Presentación'),
('Catálogo Electrónico'),
('Certificación Presupuestal'),
('Cesión de Derechos'),
('Clasificadores'),
('Código CIIU'),
('Competencias de Perú Compras'),
('Compra Agregada'),
('Compra asistida'),
('Compra Individual'),
('Compra Ordinaria'),
('Compra por Paquete'),
('Compra por Encargo'),
('Compras Corporativas'),
('Comunicados'),
('Constancia'),
('Consultas generales / Solicitud de Información'),
('Convocatoria de Personal CAS'),
('Convocatorias'),
('Compras financiadas por el BID'),
('Correspondencia / Notificaciones'),
('Cotizaciones'),
('Creación de Valores'),
('Datos de Representante de Marca'),
('Denuncia'),
('Depósito de Garantía de Fiel Cumplimiento'),
('Devolución de Garantía de Fiel Cumplimiento'),
('Difusión DCEME'),
('Directivas'),
('Directorio Institucional'),
('Ejecución Contractual'),
('Entrega de Bienes'),
('Estado de Orden de Compra'),
('Estimador de precios'),
('Evaluación y Subsanación de Fichas Producto'),
('Exceptuación de Compra por Catálogo Electrónico'),
('Exclusión e Inclusión de Proveedores'),
('Expediente de Contratación'),
('Fichas Producto'),
('Gran Compra'),
('Homologación'),
('ID Certificación'),
('Incidencia'),
('Incorporación de nuevos productos'),
('Incumplimiento de Pago'),
('Inscripción Proveedor'),
('Ley y Reglamento de Contrataciones Públicas'),
('Liberación de Certificado Presupuestal'),
('Listado de Bienes y Servicios comunes'),
('Manual de Operatividad'),
('Mejora de Ofertas'),
('Mesa de Partes'),
('Modificación de reserva del CCP'),
('Monto mínimo de atención'),
('Montos mínimos de Contratación'),
('Multiusuarios'),
('Notificación de Transparencia'),
('Obligatoriedad de Contratar por Catálogo Electrónico'),
('Ofertas no Adjudicadas'),
('Operatividad del Catálogo Electrónico'),
('Orden de Compra'),
('Pladicop'),
('Plazos de Entrega'),
('Presentación de Ofertas'),
('Previsión presupuestal'),
('Productos falsificados'),
('Proforma'),
('Reclamo'),
('Recurso Impugnatorio'),
('Rechazo de OCAM'),
('Registro de nuevos Proveedores'),
('Reglas de Operatividad'),
('Requerimiento'),
('Resolución de Orden de Compra'),
('Resultado de Proveedores'),
('Sanción TCP'),
('Seguimiento de Trámite / Correo'),
('Semáforo'),
('Solicitud de Capacitación'),
('Solicitud de reunión'),
('Subasta Inversa Electrónica'),
('Tipo de Cambio'),
('Tipo de Contratación'),
('Tipo de Entrega'),
('Transparencia'),
('Uso de imagen Institucional'),
('Vigencia del Acuerdo Marco');

INSERT INTO ccrepo.PERUCOMPRAS_organo_atencion (nombre) VALUES
('OAUGD'),
('DCEME'),
('DE'),
('DTEN'),
('OA'),
('OC'),
('OAJ'),
('OTI'),
('OCI'),
('GG'),
('Jefatura');

INSERT INTO ccrepo.PERUCOMPRAS_satisfaccion_servicio (nombre) VALUES
('Muy Malo'),
('Malo'),
('Regular'),
('Buena'),
('Excelente');

INSERT INTO ccrepo.PERUCOMPRAS_region (nombre) VALUES
('Amazonas'),
('Áncash'),
('Apurímac'),
('Arequipa'),
('Ayacucho'),
('Cajamarca'),
('Callao'),
('Cusco'),
('Huancavelica'),
('Huánuco'),
('Ica'),
('Junín'),
('La Libertad'),
('Lambayeque'),
('Lima'),
('Loreto'),
('Madre de Dios'),
('Moquegua'),
('Pasco'),
('Piura'),
('Puno'),
('San Martín'),
('Tacna'),
('Tumbes'),
('Ucayali');

INSERT INTO ccrepo.PERUCOMPRAS_acuerdo_marco (nombre) VALUES
('EXT-CE-2024-1 Baterías, pilas y accesorios'),
('EXT-CE-2024-2 Equipos multimedia y accesorios'),
('EXT-CE-2024-3 Materiales e insumos de limpieza y papeles para aseo y limpieza'),
('EXT-CE-2022-5 Computadoras de escritorio, portátiles y escánere'),
('EXT-CE-2021-6 Impresoras; consumibles; repuestos y accesorios de oficina'),
('EXT-CE-2021-7 Útiles de escritorio, papeles y cartones'),
('EXT-CE-2024-10 Llantas, neumáticos y accesorios'),
('EXT-CE-2024-12 Pinturas, cerámicos, pisos, tuberías, sanitarios, accesorios y complementos'),
('EXT-CE-2024-13 Equipos de aire acondicionado, similares y accesorios'),
('EXT-CE-2024-14 Luminarias, materiales y cables eléctricos'),
('IM-CE-2020-15 Servicio de emisión de boletos aéreos'),
('EXT-CE-2024-16 Accesorios domésticos y bienes para usos diversos'),
('EXT-CE-2024-17 Bebidas no alcohólicas'),
('EXT-CE-2024-18 Cereales, aceite, azúcares y menestras'),
('EXT-CE-2024-26 Máquinas y equipos, y herramientas para jardinería, silvicultura y agricultura'),
('EXT-CE-2024-28 Calzado y botas'),
('No aplica');

INSERT INTO ccrepo.PERUCOMPRAS_tipo_usuario (nombre) VALUES
('Entidad'),
('Proveedor'),
('Marca'),
('Otros');

INSERT INTO ccrepo.PERUCOMPRAS_tipo_documento (nombre) VALUES
('RUC'),
('DNI');

INSERT INTO ccrepo.PERUCOMPRAS_estado_consulta (nombre) VALUES
('Atendido'),
('Pendiente');

INSERT INTO ccrepo.PERUCOMPRAS_valoracion_atencion (nombre) VALUES
('Califica'),
('No califica');
